{
 "title": "DASHBOARD #4 [UNIDO]",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "PARAM_001", "query": "GET" },
   { "name": "PARAM_002", "label": "Variable de tipo CONSTANT", "query": "GET" },
   {
    "name": "PARAM_004",
    "label": "Variable de tipo QUERY",
    "query": "label_values(http_client_requests_seconds_count, status)"
   }
  ]
 },
 "panels": [
  {
   "title": "DASHBOARD #1",
   "type": "graph",
   "description": "DASHBOARD #1",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "http_client_requests_seconds_count{ method=~\"$PARAM_001\" }"
    }
   ]
  },
  {
   "title": "DASHBOARD #3",
   "type": "gauge",
   "description": "DASHBOARD #3",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "avg( http_client_requests_seconds_count ) by( job )"
    }
   ]
  },
  {
   "title": "DASHBOARD #2",
   "type": "graph",
   "description": "DASHBOARD #2",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "http_client_requests_seconds_count{ job=~\".*\",method!=\"GET\" }"
    }
   ]
  }
 ]
}